### ISSUE TITLE
Chrome - TypeError: Cannot read property 'getElementsByClassName' of null

### ISSUE THREAD

**Issue by zmazula** [berzniz/github_pr_tree#100]
Hi,

We very like your github extension, but it stopped working after the weekend.
![image](https://user-images.githubusercontent.com/8101139/75656702-c9c77b00-5c64-11ea-8aa6-b97dbd8e78ed.png)

**Chrome** : Version 80.0.3987.122 (Official Build) (64-bit)
**Github enterprise**: GitHub Enterprise Server 2.17.16

Could you please check what would be the problem? Or do you need any other details about the error?
Thanks!
Zoltan

**Comment by themakshter** [comment]
Can confirm, facing the same issue

**Comment by berzniz** [comment]
Thanks for reporting. It seems regular GitHub and Enterprise GitHub are different at this point in this. We'll try provide an update that supports both.

**Comment by berzniz** [comment]
Just a quick question - which version of the Chrome Extension do you have installed? 1.0.25 or 1.0.26? You can check by right-clicking on the extension icon and choose "Manage Extensions"

**Comment by zmazula** [comment]
> Just a quick question - which version of the Chrome Extension do you have installed? 1.0.25 or 1.0.26? You can check by right-clicking on the extension icon and choose "Manage Extensions"

I've used and reinstalled the 1.0.26, but it doesn't work.

**Comment by pportnoy** [comment]
Same issue here, GitHub Enterprise.

**Comment by chrischdi** [comment]
Same here:
Extension: 1.0.26
GH Enterprise: 2.19.3

**Comment by vazhem** [comment]
Same issue. It was working before. Now it does not...

Extension: 1.0.26
Chrome: 80.0.3987.132 (64-bit)
GH Enterprise: 2.17.7

**Comment by FJancsi** [comment]
Same issue here:
Extension: 1.0.26
Chrome: 80.0.3987.132
GH Enterprise: 2.17.16

**Comment by berzniz** [comment]
Will be available in version 1.0.27 (thank you @shatee)

**Comment by zmazula** [comment]
> Will be available in version 1.0.27 (thank you @shatee)

Woow, this was so fast! Amazing, thank you @berzniz and @shatee!

**Comment by berzniz** [comment]
The update has been approved in the store (version 1.0.27) - Chrome auto-updates, but you can click manually update it from the Extensions settings page of Chrome.

If you're enjoying the extension, please consider leaving a review: https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc
