### ISSUE TITLE
add option to mark files / directories as viewed from the tree

### ISSUE THREAD

**Issue by jossef** [berzniz/github_pr_tree#104]
![image](https://user-images.githubusercontent.com/1287098/78708709-3ba57b00-791b-11ea-9f27-4c7a9c4dcc12.png)

It would be useful to add an option to mark files and directories as viewed from the tree.
I'm thinking about a right-click context menu or a check button near each item 

- single files
- directories - marks all files inside (multiple levels)

I can submit a PR if needed

**Comment by berzniz** [comment]
Hi @jossef, thanks for the suggestion.

In general, I'd like to keep the scope of the extension small and to not duplicate any feature already available on the page. If there are more voices advocating for this, we can reconsider.
