### ISSUE TITLE
Search by exactly  file name doesn't work

### ISSUE THREAD

**Issue by djdeimon** [berzniz/github_pr_tree#109]
**ISSUE:**
When user starts to search file by provide exactly file name - results not shown.
I think that search shouldn't be case sensitive.

In case below I try to find `DataGrid.js`

![screenshot-github com-2020 04 23-08_03_03](https://user-images.githubusercontent.com/5168044/80064973-9654ee80-8539-11ea-8801-aeb959613bc9.gif)

**Comment by berzniz** [comment]
Thanks for reporting. If anyone wants to fix this (should be a simple fix) - just issue a PR. Otherwise, I can get it fixed on the next version
