### ISSUE TITLE
How to re-open tree after closing

### ISSUE THREAD

**Issue by msorens** [berzniz/github_pr_tree#115]
Other than doing a browser refresh, is there a key, button, or mouse action that can re-open the tree once you close it via the "X" button?

**Comment by berzniz** [comment]
Hi @msorens - thanks for providing the feedback.

As GitHub pages load quite fast, I think doing a refresh (using `⌘`+`R`) is a reasonable choice.

Adding shortcuts requires more permissions and the tradeoff doesn't seem worth it. Open for a different take. Currently closing this one.

**Comment by msorens** [comment]
Per your points, I agree that adding a shortcut is probably not worth it. But there are other options. The UX (user experience) could be improved if instead of completely removing the tree from the page you provide an on-screen button to re-open it. There are several reasons for this:
1. It will save some users a lot of confusion about "how do I re-open this?" (like it caused me :grin:).
2. Convention for closing a sidebar is to leave a "handle" on the edge of the screen to re-open it, so just disappearing goes against convention.
3. Browser refresh is often not convenient. People's perception of "fast" responsiveness (as in reloading the GitHub page) can vary tremendously.
