### ISSUE TITLE
Selected item out of sync

### ISSUE THREAD

**Issue by Hacksore** [berzniz/github_pr_tree#118]
The selected item in the tree seems to be out of sync and typically not the item I clicked on.

It seems like a bug to me but opening an issue to track this nevertheless and to get some feedback from others.

![gif](https://i.imgur.com/7ojrvvl.gif)

**Comment by berzniz** [comment]
Thanks for reporting. It seems like GitHub doesn't scroll all the way when navigating using links (URL change), so it goes out of sync.

If anyone wants to try and fix it, I'll appreciate a PR

**Comment by aramperes** [comment]
I'd love to help with this. My understanding is that the tree highlights the first file visible in the viewport.

https://github.com/berzniz/github_pr_tree/blob/42f2f05e0a8f488877dcae3bb181567f629e3da1/src/js/components/tree/index.jsx#L121-L126

To fix this, I would suggest prioritising an element with the `:target` pseudo-class, and check if it's in the viewport. If it's not, default back to the current logic (first visible file).

The behaviour would feel more natural: clicking on the tree item would select the right one, and scrolling up the page would scroll up in the tree as well.

**Comment by berzniz** [comment]
Will be in included in 1.0.32
