### ISSUE TITLE
Scrollbar bug in Chrome 67

### ISSUE THREAD

**Issue by Ky6uk** [berzniz/github_pr_tree#12]
Scrollbar appears on top of the `Jump to... 🔽 ` popup.

![screen shot 2018-05-04 at 11 38 37](https://user-images.githubusercontent.com/46930/39619375-4bb8cd6e-4f90-11e8-8cbf-8ec6990f3d71.png)

**Comment by berzniz** [comment]
Thanks for reporting. Is this a Chrome Canary release? Do you think it's a bug in Chrome or the extension code?

**Comment by Ky6uk** [comment]
Yeah. It looks like a Chrome/Github bug. Because other scrollbars also render on top of bubbles.
