### ISSUE TITLE
[Feature request] Add green check to directories when all files are checked

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [berzniz/github_pr_tree#122]
When I review a PR and click on "Viewed", nice green check is added to the file name.

I suggest to add the same green check to the directory in case that all files and subdirectories in that directory are already checked. To see what directory trees are already reviewed and can be collapsed for easier navigation.

Another idea is to change the collapsing triangle to green color to keep the graphics simple. Because I will collapse those.

This would significantly help to review bigger PRs with many updated files.

**Comment by berzniz** [comment]
Sounds like a good idea. I'm open to accepting a pull request for this.
