### ISSUE TITLE
[Feature request] Bold file names that have not yet been viewed

### ISSUE THREAD

**Issue by Katarn** [berzniz/github_pr_tree#133]
As soon as you click on the file name in the tree and it will open, change the font style to the usual one. Of course, when you reload the page, you need to remember which files were viewed earlier.

If the pull request has been updated, only the files that have been updated should be bold again.

**Comment by berzniz** [comment]
Thanks @Katarn for the suggestion. While this makes a lot of sense, and is similar to how email read/unread is working, GitHub already have their own functionality of "viewed".

I do not wish to create a different experience that will compete with the built-in one. Viewed files are already shown in the tree with a checkmark next to them.
