### ISSUE TITLE
[Feature request] Dark mode

### ISSUE THREAD

**Issue by JamesG3D** [berzniz/github_pr_tree#137]
Github has a dark mode now: https://github.com/settings/appearance
Would be cool if better pull request had it too!

Currently looks a bit naff with dark mode:
https://imgur.com/rR2jYsb

**Comment by tuchk4** [comment]
btw, you can open settings and enable dark mode for files tree. 
It will be a bit different from Github's colors, but better than keep it white :D

![image](https://user-images.githubusercontent.com/5140611/101621279-3a829b80-3a1e-11eb-9e64-1e4a34e15850.png)

**Comment by berzniz** [comment]
Hi @JamesG3D - thanks for reporting. And thanks @tuchk4 for providing the solution.

I am open to accept PRs that will integrate better with the new colors. It could even be removing the "Dark mode / Light mode" selection from the extension and just base it on the current appearance of GitHub.

**Comment by painhardcore** [comment]
Yep, It will awesome for styles to match.

**Comment by berzniz** [comment]
Closed by #139 (thanks @voliva) and will be included in version 1.0.33
