### ISSUE TITLE
Show files under one folder only

### ISSUE THREAD

**Issue by AlbertoSadoc** [berzniz/github_pr_tree#144]
Hi, thanks for this very useful extension.

I think it would be great if after clicking in a folder only the file under that folder are displayed.

We tend to put files with similar functionality under the same folder, therefore clicking on that folder would show all those files, rather than clicking one by one on the file tree.

Thanks.

**Comment by berzniz** [comment]
Thanks for the feedback item. I extension is designed to give a similar experience of an IDE, and IDEs usually do not have this behavior when clicking on folders.
