### ISSUE TITLE
Option to enable "hide whitespace changes" by default

### ISSUE THREAD

**Issue by pladaria** [berzniz/github_pr_tree#145]
Github has this option

![image](https://user-images.githubusercontent.com/579417/107227418-a338c500-6a1b-11eb-9493-13172a025251.png)

But it doesn't remember your preference and if you change it, a reload is needed.

**Comment by berzniz** [comment]
Hi. Thanks for the idea. I'd except a PR with an added option to enforce ignoring-whitespace if anyone is up for the challenge

**Comment by mploigt** [comment]
I never did a chrome extension, but if someone want to do it, here you can see what have to be done: https://github.com/jackchuka/chrome-extension-github-whitespace

**Comment by berzniz** [comment]
If anyone wants to submit a PR for this, let's re-open it. Closing for now
