### ISSUE TITLE
bug: tree view panel appears in a PR's checks tab

### ISSUE THREAD

**Issue by roikoren755** [berzniz/github_pr_tree#170]
![image](https://user-images.githubusercontent.com/26850796/131476675-2fde08fa-cde4-4ee2-b002-d0e5d44d95f7.png)

As can be seen in the screenshot above, the side panel appears, and empty, in a PR's checks tab, and hides the checks side panel underneath it.

**Comment by berzniz** [comment]
Thanks for reporting. I'm open for PRs that address this

**Comment by berzniz** [comment]
Will be available in version 1.0.35
