### ISSUE TITLE
Not working on GitHub Enterprise

### ISSUE THREAD

**Issue by matheuskiser** [berzniz/github_pr_tree#171]
Tree is not showing up anymore on our GitHub Enterprise domain. I've tried it on Mac/Windows and Chrome/Firefox and I couldn't see the tree anymore. This has also occurred to coworkers of mine in the past month or so. Not sure if something has changed or not.

**Comment by epilande** [comment]
Seeing the same issue. The extension isn't working on GitHub Enterprise, but it is working on regular public GitHub. 

Seeing the following console error: 

![image](https://user-images.githubusercontent.com/3210082/131568879-1ebaf95d-0bfc-4f41-9a49-7ff31690b606.png)

**Comment by portsmouth** [comment]
Debugger at point of exception, with (redacted) callstack:

![image](https://user-images.githubusercontent.com/2774364/131666148-e1db9437-96af-437e-9ff5-d95f2ed1d01b.png)

**Comment by portsmouth** [comment]
Debugger at point of exception, with (redacted) callstack:

![image](https://user-images.githubusercontent.com/2774364/131666388-7c5c073b-af68-4fa8-9863-7dca03391455.png)

**Comment by berzniz** [comment]
Can anyone with access to a GitHub enterprise account test the extension that is currently on the master branch? A fix (#173) was just merged for the `publicPath` error, but I'm not sure it is 100% solving this issue.

**Comment by portsmouth** [comment]
How would one test the current master? Is it doable via the Chrome extensions manager?

**Comment by berzniz** [comment]
> How would one test the current master? Is it doable via the Chrome extensions manager?

This is listed on the README file.

**Comment by berzniz** [comment]
This was verified by @halfbro (thank you) in #173 -- will be available in version 1.0.35

**Comment by matheuskiser** [comment]
Thanks all! Works great on FIrefox too :)
