### ISSUE TITLE
Support for dynamic width of sidebar

### ISSUE THREAD

**Issue by romanlex** [berzniz/github_pr_tree#18]
Hello, I think if sidebar with tree of source will has dynamic width and user can change this width it is better than open/close sidebar. What you think?

**Comment by berzniz** [comment]
Sounds like a good idea. Go for it and I'll review the PR

**Comment by berzniz** [comment]
This was added to https://github.com/berzniz/github_pr_tree/releases/tag/1.0.11

**Comment by berzniz** [comment]
Fixed in 1.0.13
