### ISSUE TITLE
Dark mode auto-toggle not working

### ISSUE THREAD

**Issue by DiljotSG** [berzniz/github_pr_tree#182]
I currently have my GitHub in "Sync with System" theme mode and I have my GitHub in "Dark High Contrast" for when my system is in dark mode. Better Pull Request does not respect this setting. When I switch my GitHub to "Single Theme" and disable "Sync With System" only then does Better Pull Request switch to dark styles. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/19293725/135885775-c89fc9c4-88f1-4c63-8fa6-fbe8934ad8c8.png)

**Comment by berzniz** [comment]
Hi @DiljotSG, thanks for reporting.

I'd gladly accept a PR for this if anyone is available to work on it.

**Comment by jcheek** [comment]
+1.  I have the same issue and would love to see a fix.  If I were to poke around in the code and see if I could fix this, is there any guidance where to start? @berzniz

**Comment by ryanrishi** [comment]
PR for the fix: https://github.com/berzniz/github_pr_tree/pull/186

**Comment by berzniz** [comment]
Thanks @ryanrishi - this planned for the next release

**Comment by berzniz** [comment]
This will be included soon in 1.0.36
