### ISSUE TITLE
Weird margin between file list and files

### ISSUE THREAD

**Issue by damemi** [berzniz/github_pr_tree#205]
Using version `1.0.36` on chrome, there is a new weird margin between the file tree and files themselves that seems to be due to the `#files` element setting `margin-left: 347px;` (see below screenshots)

![Screen Shot 2022-03-21 at 9 22 45 AM](https://user-images.githubusercontent.com/1839101/159270179-6774daf8-0ff8-467f-b675-4073a88bada4.png)
![Screen Shot 2022-03-21 at 9 23 20 AM](https://user-images.githubusercontent.com/1839101/159270181-ebd3b6e9-26f0-43ed-bed3-0e2644f4f508.png)

**Comment by dreamcryer** [comment]
Probably due to the new beta feature GitHub is introducing.
<img width="420" alt="Screen Shot 2022-03-22 at 3 53 56 PM" src="https://user-images.githubusercontent.com/2136468/159590044-7236acbe-a0ff-4301-856a-ffebad752341.png">

**Comment by fp-jcorriveau** [comment]
When disabling the extension, GitHub now has a beta file tree of its own

**Comment by damemi** [comment]
Ah, that's neat. I'll have to give it a try. This extension has worked really great for me for a couple years now, much easier to use than some of the others that are available.

**Comment by ptous** [comment]
I do prefer this extension's tree, so if this could be made compatible (avoiding the margin in this issue's report) I would still use the extension's view. I miss both the diff stats and the file type icons.

**Comment by berzniz** [comment]
You have both trees enabled (GitHub and this extension). I do not think this deserves a fix.

Fix: disable the Beta GirHub tree

<img width="908" alt="image" src="https://user-images.githubusercontent.com/170214/162422113-7559849f-6060-4ea0-8ed4-9bb51e6cc535.png">

**Comment by damemi** [comment]
Oh cool, thanks @berzniz I didn't realize I could disable the GH file tree. Thanks for all of your work on this!

**Comment by damemi** [comment]
@berzniz it looks like Github has removed the option to disable the pull request file tree (maybe the feature is moving out of beta? or I'm just missing the option somewhere else)

Still, the Github file tree is really lacking in features so I want to keep using this extension if I can. Are there plans to make it compatible with the GH file tree?

**Comment by damemi** [comment]
Whoops, sorry for the spam. Just found that the option to hide GH's file tree moved thanks to https://github.com/berzniz/github_pr_tree/issues/202
