### ISSUE TITLE
Stopped working for enterprise users | version 1.0.37 

### ISSUE THREAD

**Issue by matheuskiser** [berzniz/github_pr_tree#211]
Extension was working up until sometime this morning. It might have updated or something. Now, no file tree shows up on the left side of the PR.

I'm on Chrome version 100.0.4896.75 (Official Build) (arm64) using Better Pull Request version 1.0.37.

I've tried to disable it for my enterprise project and re-enable it, but it didn't work.

**Comment by berzniz** [comment]
1. GitHub now have their own file tree in the `Feature Preview` area. Worth checking if that is a good replacement.
2. I will accept PRs that solves this. I have no GitHub Enterprise account to check with.

**Comment by matheuskiser** [comment]
_GitHub now have their own file tree in the Feature Preview area. Worth checking if that is a good replacement._
Unfortunately it's not available in my enterprise, ugh

_I will accept PRs that solves this. I have no GitHub Enterprise account to check with._
I'm happy to test any fixes

**Comment by matheuskiser** [comment]
It seems to have been resolved somehow. Chrome updated this morning, so maybe that was it.

**Comment by gforien** [comment]
Same problem here.
Chrome was up-to-date (version 100.0.4896.127 x86_64) and the extension was also up-to-date.
After uninstalling / reinstalling from the Chrome Web Store it works again ✨
