### ISSUE TITLE
The sidebar lowers the diff code's line length

### ISSUE THREAD

**Issue by dsbonev** [berzniz/github_pr_tree#23]
Sidebar is rendered next to the diff, it pushes the code to the right thus making the code's line shorter. This is problematic as horizontal scrolling is applied if I need to see the full code line. There is no need for horizontal scrolling when this extension is not loaded. Let's move the extension's rendering position outside the diff tab, e.g. taking inspiration from `octotree`'s rendering position.

### Without sidebar
![image](https://user-images.githubusercontent.com/1313633/47270808-af15ca00-d579-11e8-8c46-e8109b7f2854.png)

### With sidebar
![image](https://user-images.githubusercontent.com/1313633/47270819-ec7a5780-d579-11e8-84cf-eb395c7d4774.png)

### With octotree sidebar
![image](https://user-images.githubusercontent.com/1313633/47270835-3105f300-d57a-11e8-9cd7-6c137ab07675.png)

**Comment by berzniz** [comment]
Thanks for reporting. Can you provide a link to the PR in the screenshots?

**Comment by dsbonev** [comment]
@berzniz here is the link to the PR and the file from the screenshots https://github.com/berzniz/github_pr_tree/pull/22/files#diff-0cd9063dc2d8497da88d3e184450edb6

**Comment by berzniz** [comment]
I usually use the `Diff settings`:`Split` option, so I normally don't run into this. When I use the `Unified` option it happens on the regular view, but clicking the expand button of the extension (next to the close button) solves it.

1. Does it solve it for you as well? If so, we can have the expanded option as default.
2. Does Octotree overlays over the code? if so, I prefer not to go there.
3. I'm open for pull requests for this

**Comment by dsbonev** [comment]
> 1. Does it solve it for you as well? If so, we can have the expanded option as default.

It solves it, consider adding an option for this.
> 2. Does Octotree overlays over the code? if so, I prefer not to go there.

I don't think it overlays over the code, the code is rendered in the center of the page while the Octotree is rendered on the free space that GitHub's site layout has on the left.
> 3. I'm open for pull requests for this

Sure, thanks, everyone is invited to work on this one. I actually made it work for myself by installing `Wide Github` Chrome extension.

**Comment by berzniz** [comment]
Closing this as there's a solution and no one seems eager to provide a PR for this. We can re-open if there are requests from users here.
