### ISSUE TITLE
Suggestion PR comments squashed when sidebar is open

### ISSUE THREAD

**Issue by StormPooper** [berzniz/github_pr_tree#24]
When the sidebar is open, the new Suggestions PR comment gets squashed up in the comment preview. Examples below. Closing the sidebar fixes it.

With the sidebar closed:
![image](https://user-images.githubusercontent.com/1657182/48713817-300fc200-ec09-11e8-9d9c-7d1324f2a7b0.png)

### With the sidebar open:
![image](https://user-images.githubusercontent.com/1657182/48713803-26865a00-ec09-11e8-9337-be800173bd6b.png)

**Comment by berzniz** [comment]
Thanks for reporting. Can you please share a link to the PR in the test case?

**Comment by StormPooper** [comment]
Sadly not, as it's a private work repo, but I've had it happen on other PRs too so you should be able to see it on any you have open. If you can't reproduce it let me know and I'll set up a fresh one.

**Comment by berzniz** [comment]
Fixed in 1.0.13
