### ISSUE TITLE
Enterprise Github

### ISSUE THREAD

**Issue by mistermendez** [berzniz/github_pr_tree#3]
Cool extension!

This doesn't work with the enterprise version of Github I use at work. 

github.company.com

**Comment by berzniz** [comment]
Thanks for reporting.

Is GitHub enterprise the same, just on a different domain? If so, a simple fix will be asking for permissions on all `*://github.*.*/*` - do you think that will work?

**Comment by berzniz** [comment]
Unfortunately, chrome extensions doesn't allow whitelisting schemes such as `*://github*/*`. I'm open to suggestions.

**Comment by gwevans** [comment]
@berzniz I am trying to get this working for my specific company by developing locally, but I seem to be missing something.

1. I cloned the repo
2. Ran yarn install
3. Ran yarn start
4. Went to `src/manifest.json` and changed the `matches` key to `"*://*.github.mycompany.com/*"`
5. Went into the chrome extensions, refreshed the tab, and hit update (the reload extensions button seems to be gone in my Chrome version (69)

Am I missing something?

**Comment by berzniz** [comment]
@gwevans Just making sure:

1. You have to enable Developer Tools:
![image](https://user-images.githubusercontent.com/170214/45916837-ddb65d00-be74-11e8-8009-03b9f835a48d.png)

2. Load the unpacked extension:
![image](https://user-images.githubusercontent.com/170214/45916841-e870f200-be74-11e8-9b4c-4ffba328bf26.png)

3. Choose the `/build` folder

4. This is the extension with your updated manifest

----

If you did all that already, I can try to look into it again

**Comment by gwevans** [comment]
@berzniz Thanks, that did the trick. Awesome tool by the way.

**Comment by leocaseiro** [comment]
Maybe using the same approach as the https://github.com/sindresorhus/refined-github which is to add a URL for each github enterprise?

**Comment by mryan43** [comment]
any news on this ? I would really love this feature !
BTW make sure that you support domains that do not end in ".com", my org is ".ch" :)

**Comment by leocaseiro** [comment]
A quick update is that Octotree works quite similar this app and it’s working on GitHub enterprise.

PS: the tree is not as good as this extension though

**Comment by berzniz** [comment]
I was actually going to implement it (following @leocaseiro resources) but got a bit tied up with my real work. I'm planning to add it, hopefully in the next few days

**Comment by berzniz** [comment]
Included in version 1.0.14
(rate on the [Chrome store](https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc) if you enjoy the extension)

**Comment by mryan43** [comment]
Thanks a lot for this ! works like a charm !

**Comment by mryan43** [comment]
> A quick update is that Octotree works quite similar this app and it’s working on GitHub enterprise.
> 
> PS: the tree is not as good as this extension though

I agree ! and I also prefer this extension !
