### ISSUE TITLE
Feature Request: It would be good if you could filter for a specific file within the tree view

### ISSUE THREAD

**Issue by markwalsh-liverpool** [berzniz/github_pr_tree#38]
As title.

**Comment by berzniz** [comment]
That's a good idea. I'm open to include PRs addressing this request.

**Comment by danielkman** [comment]
@berzniz Hey, I'll be happy to work on it (Not a react developer but I'll give it a try)

**Comment by berzniz** [comment]
Go for it 👍 This could be good practice for learning React

**Comment by berzniz** [comment]
Included in 1.0.15. Thanks @danielkman !

**Comment by danielkman** [comment]
👍
