### ISSUE TITLE
Feature Request: keep file tree always in view when switching between files

### ISSUE THREAD

**Issue by planetsizebrain** [berzniz/github_pr_tree#39]
It would be nice if the file tree could be kept in view when you switch between source files (like the BitBucket Tree Plugin does: https://chrome.google.com/webstore/detail/bitbucket-diff-tree/pgpjdkejablgneeocagbncanfihkebpf?hl=en).

Thx already for the great plugin that makes Github PRs much more bearable.

**Comment by planetsizebrain** [comment]
Some investigation shows that the uBlock Origin plugin seems to be the cause of this somehow.

**Comment by berzniz** [comment]
Thanks for reporting! This will probably help anyone who encounter this 👍

**Comment by planetsizebrain** [comment]
You're welcome. It's something in the 'cosmetic filtering' part of the uBlock Origin plugin. If I turn those off for github.com your plugin works like a charm.
