### ISSUE TITLE
Open / close tree icons reverse to norm

### ISSUE THREAD

**Issue by mbrookes** [berzniz/github_pr_tree#4]
Genius extension!

My gut instinct though was that the open/close arrows are backwards. Looking around, here are a few examples that are opposite to github_pr_tree. (Not an exhaustive search, but I didn't come across any that were the same way around.):

![image](https://user-images.githubusercontent.com/357702/35810707-84325bde-0a84-11e8-99e2-eb64ee3ef0fe.png)

![image](https://user-images.githubusercontent.com/357702/35810548-02c694de-0a84-11e8-989a-62b8d5f67e32.png)

![image](https://user-images.githubusercontent.com/357702/35810601-23e60f46-0a84-11e8-8859-c58301879955.png)

![image](https://user-images.githubusercontent.com/357702/35810645-47797c5e-0a84-11e8-95e1-74552b0adc94.png)

![image](https://user-images.githubusercontent.com/357702/35810651-54bd80e0-0a84-11e8-994f-c61717d313f9.png)

![image](https://user-images.githubusercontent.com/357702/35810759-a937de2c-0a84-11e8-8166-70ef195bb65f.png)

**Comment by berzniz** [comment]
Wow... can't argue with that 💯 

Thanks for reporting - I'll change to the standard behavior.
