### ISSUE TITLE
Sidebar does not show all changed files

### ISSUE THREAD

**Issue by arki91** [berzniz/github_pr_tree#44]
The sidebar doesn't show all changed files.
![issue_pic1](https://user-images.githubusercontent.com/3234707/54107767-5c2e9900-43da-11e9-80e8-f94f20a5c4ce.PNG)
![issue_pic2](https://user-images.githubusercontent.com/3234707/54107803-75374a00-43da-11e9-94df-318e35a93b4f.PNG)

**Comment by berzniz** [comment]
Thanks for reporting. Can you provide the link to that PR? or is it private?

**Comment by arki91** [comment]
Unfortunately its a PR on a private repository :(

**Comment by aleksashyn** [comment]
The same problem with GitHub Enterprise

**Comment by scilone** [comment]
fixed here https://github.com/berzniz/github_pr_tree/pull/46

**Comment by berzniz** [comment]
Fixed in #46
