### ISSUE TITLE
Maximum width should only apply to `Files changed` tab

### ISSUE THREAD

**Issue by nesl247** [berzniz/github_pr_tree#45]
I don't want every part of a PR to be max width. This is because it stretches out the comments and requires more left -> right eye movement to read it. I was hoping that the max width feature would only apply to `Files changed` but it doesn't. Since the button is only on this page, it should apply only to this page.

P.S. the max width icon isn't very apparent as to what it does to me. Maybe there is a better icon?

**Comment by scilone** [comment]
fixed here https://github.com/berzniz/github_pr_tree/pull/48

**Comment by nesl247** [comment]
Thanks @scilone!
