### ISSUE TITLE
Remember fullscreen setting

### ISSUE THREAD

**Issue by nesl247** [berzniz/github_pr_tree#50]
It would be great if the fullscreen setting was remembered. This way I don't have to click it on every PR.

**Comment by berzniz** [comment]
Would indeed. I'm open for PR submissions for this

**Comment by berzniz** [comment]
Fixed by #63 (included in version 1.0.21)

**Comment by thockin** [comment]
Awesome!  Is there a list of improvements in each release?

**Comment by berzniz** [comment]
Yes. Read the readme file, it links to the change log
