### ISSUE TITLE
PR tree refreshes constantly

### ISSUE THREAD

**Issue by thockin** [berzniz/github_pr_tree#55]
Open a PR, such as https://github.com/kubernetes/kubernetes/pull/74447/files

Hover in the PR tree over a file: observe that it refreshes and flickers non-stop.

Try to click the expander arrow: observe that it doesn't fold up or if it does it immediately unfolds again

**Comment by thockin** [comment]
Weird.  I disabled all my other extensions and see that it works.  I have re-enabled them all and it still works.

**Comment by berzniz** [comment]
Thanks for reporting, even if it resolved itself somehow. It could be that you had an old version with these issues (we had a flickering issues on an old version) and it got updated.

**Comment by thockin** [comment]
I think it was conflicting with another plugin which also tried to
horizontally expand but chose a different value, so they fought.  If
this extension auto-expanded upon page load, I would be super happy :)
