### ISSUE TITLE
Shows up as empty space when on non-PR commit page

### ISSUE THREAD

**Issue by kamranahmedse** [berzniz/github_pr_tree#6]
Good job on the extension, love it so far :)

Not a biggie, but on the [commit detail page](https://github.com/facebook/react/commit/49b0ca1b836751ae78fd191286b9eb3bf2be385b) it takes up the space but the tree doesn't show up.

![image](https://user-images.githubusercontent.com/4921183/36035026-0f5d9064-0db6-11e8-8bbf-da0df6110d6a.png)

**Comment by robinwkurtz** [comment]
Bigger but still minor issue on `/conficts`

**Comment by berzniz** [comment]
Thanks. Will fix in next update

**Comment by berzniz** [comment]
Fixed in version 1.0.4
