### ISSUE TITLE
Link stop working after first click when another theme is applied

### ISSUE THREAD

**Issue by Snazzie** [berzniz/github_pr_tree#64]
Hi, there's seems to be a conflict with my dark theme for github and your side bar CSS.
https://github.com/acoop133/GithubDarkTheme 

Your sidebar works perfectly when the theme is not active. when the theme is active, after the first click on the link, the sidebar becomes completely un-interactable. 

I will take a look why its so when i have some time, but if you want to beat me to it. be my guest :P

**Comment by berzniz** [comment]
Thanks for reporting. I'll have a look when I have time, I'd love to make the extension work well with others.

**Comment by acoop133** [comment]
An update to the bug. so it would become interactive again if that panel is moved. see gif 
![2019-06-07_15-07-04](https://user-images.githubusercontent.com/19627023/59110007-0ebcbc00-8936-11e9-9618-4021c081e394.gif)

**Comment by berzniz** [comment]
This should be fixed in the next version (React key update)
