### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by yijia-zhan** [berzniz/github_pr_tree#68]
This really is just a question. This plugin is so awesome that it's making it difficult for me to switch to any non-chromium base browsers. Is there any plan to port this to Firefox?

**Comment by berzniz** [comment]
My main browser is Chrome, so I have no urgency for a port. However, I will be happy to merge a port (and take ownership of submissions to Mozilla/Firefox) if anyone is interesting in submitting a PR.

It shouldn't be that hard as both are conforming to the WebExtensions specs.

**Comment by fabianpiau** [comment]
@berzniz Someone has contributed to add Firefox support last month. Can you have a look and maybe merge the PR? https://github.com/berzniz/github_pr_tree/pull/84/files
I am very interested in this too as I'm a Firefox user :)
Thanks in advance!

**Comment by marcphilipp** [comment]
I'd also really love to have this extension for Firefox. Any news?

**Comment by berzniz** [comment]
Thanks everyone for keeping this alive. As everyone, I get busy sometimes with life and work, and while I planned to get to this earlier - I couldn't.

What would help me push this forward is code reviewing the changes, and testing on Firefox so I know the changes are working as expected and not breaking anything for Chrome users.

Once that help is provided, I'll make the time to push this to the Mozilla Add Ons website.

Anyone up for some help?

**Comment by berzniz** [comment]
Firefox is officially supported here:
https://addons.mozilla.org/en-US/firefox/addon/better-pull-request-for-github/

This is the first version 1.0.24 and we will gather feedback and improve.

Please rate it on the Firefox store if you enjoy it.

**Comment by marcphilipp** [comment]
@berzniz Awesome, thanks so much!

One minor thing: Is it just me or are the file icons somehow not working?
<img width="344" alt="Screenshot 2020-01-07 at 14 55 15" src="https://user-images.githubusercontent.com/214207/71900283-ca103200-315d-11ea-885f-b6ff0a16017f.png">

**Comment by marcphilipp** [comment]
This is from my console:

> Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.jsdelivr.net/npm/file-icons-js@1.0.3/css/style.css (“style-src”).

**Comment by berzniz** [comment]
Yeah, it seems like a bug should be opened for that. I honestly struggled a bit to get it to work on Firefox, so haven't checked all features.

Should probably be fixed by declaring it in the manifest.json

**Comment by marcphilipp** [comment]
I created a new issue: https://github.com/berzniz/github_pr_tree/issues/89
