### ISSUE TITLE
The "View entire file" and "Github Desktop open" icon tooltips are rendered behind the top status bar

### ISSUE THREAD

**Issue by LightCC** [berzniz/github_pr_tree#69]
When I mouse over the "view entire file" icon and the "open in Github Desktop" icon in the upper right of the screen, their tooltips come up, but they are rendered behind the top status bar, rather than in front of it, so most of the tooltip is not visible.

![image](https://user-images.githubusercontent.com/19731713/60293151-9de14200-98ec-11e9-9684-e5d50747d8f9.png)

In the above image, you can see the black strip of the tooltip and the black "arrow" pointing down to the view icon - but the rest of the tooltip, and all its text, is not visible.

**Comment by berzniz** [comment]
Can you link to a public PR where this behavior is shown? I actually see a different design on my account (maybe I'm in a different A/B split testing group)
