### ISSUE TITLE
Tree should reflect whether a file is marked as viewed

### ISSUE THREAD

**Issue by tomdcc** [berzniz/github_pr_tree#70]
Github just shipped a feature to [keep track of viewed files](https://github.blog/2019-07-01-mark-files-as-viewed/). Showing this status in some way in the tree would make navigating a PR to view files that you haven't yet reviewed even easier.

Crucible does this by marking un-viewed files in bold. That is one approach, but really any way to visually distinguish views/unviewed files would be fine.

**Comment by berzniz** [comment]
Sounds like a good idea. I'm open for PRs if anyone wants to go for it

**Comment by berzniz** [comment]
Available in version 1.0.23 - thanks everyone

Closed by #83
