### ISSUE TITLE
File tree shows initial file layout when moving files

### ISSUE THREAD

**Issue by cluhm** [berzniz/github_pr_tree#74]
On pull requests that contain moved/renamed files, the file tree tends to display the old file layout instead of showing the new name & location of the changed file(s). I put together a dummy repo and pull request showing this issue. 
https://github.com/Cluhm/test-repo/pull/2/files

In the example pull request, the test-requirements.txt file was moved from the project root in to a test directory, but the file tree still shows the file at the project root.
![Screen Shot 2019-08-12 at 8 14 11 AM](https://user-images.githubusercontent.com/7918525/62867681-7fd37380-bcd9-11e9-8dd4-176ebcee9cef.png)

**Comment by berzniz** [comment]
Thanks for taking the time to create the PR and the dummy repo -> this is really great.

It sounds reasonable to me that we will use the `test/test-requirements.txt` instead of the original `test-requirements.txt` for the tree creation.

Would you be interested in submitting a PR for this?

**Comment by cluhm** [comment]
Sure thing:
https://github.com/berzniz/github_pr_tree/pull/75

**Comment by cluhm** [comment]
I haven't had a chance to test this out too thoroughly, but the fix appears to be working as expected when looking at a couple of relatively small PRs.

**Comment by berzniz** [comment]
Closed by #75
