### ISSUE TITLE
Comments icon on files

### ISSUE THREAD

**Issue by MrReku** [berzniz/github_pr_tree#8]
Especially for PR involving many files (I have to review a PR with about 90 files involved) it is fundamental to display an icon to show which files have comments:

Final markup might look similar to:
<img width="1022" alt="screen shot 2018-03-21 at 14 33 41" src="https://user-images.githubusercontent.com/1694022/37715829-ecb97a7c-2d14-11e8-97e8-820e8e04f451.png">

.. and final result similar to:
<img width="221" alt="screen shot 2018-03-21 at 14 29 14" src="https://user-images.githubusercontent.com/1694022/37715644-7919ec00-2d14-11e8-9c49-958e01af0a30.png">

**Comment by RedSparr0w** [comment]
This would be a useful addition.
Would be great if you were able to click the comment icon and it took you to the first comment also.

**Comment by berzniz** [comment]
Added in version 1.0.7 (thanks @RedSparr0w)

**Comment by berzniz** [comment]
Please add a review on the [Chrome Web Store](https://chrome.google.com/webstore/detail/github-pull-request-tree/nfhdjopbhlggibjlimhdbogflgmbiahc/reviews) if you find this extension useful

**Comment by MrReku** [comment]
Thank you so much!!! 
Looking forward to see the 1.0.7 available and start using it.

**Comment by berzniz** [comment]
It's already up - you can force Chrome to update the extension by clicking "Update" on the while browsing to `chrome://extensions/`
