### ISSUE TITLE
Configuring URL of enterprise github that doesn't have "github" in the URL

### ISSUE THREAD

**Issue by bali182** [berzniz/github_pr_tree#81]
I saw https://github.com/berzniz/github_pr_tree/issues/3 , but our enterprise github is on a URL which doesn't have "github" anywhere in the URL. I can't seem to modify the wildcard URL on the configuration page of the extension. Is there any way to make it work with a custom url?

**Comment by berzniz** [comment]
See the main readme file. It explains how to enable any domain using a special menu option of the extension

**Comment by bali182** [comment]
Great, should have read through it 👍
