### ISSUE TITLE
File icons should work on Firefox

### ISSUE THREAD

**Issue by marcphilipp** [berzniz/github_pr_tree#89]
<img width="344" alt="Screenshot 2020-01-07 at 14 55 15" src="https://user-images.githubusercontent.com/214207/71900283-ca103200-315d-11ea-885f-b6ff0a16017f.png">

From the Browser console:
> Content Security Policy: The page’s settings blocked the loading of a resource at cdn.jsdelivr.net/npm/file-icons-js@1.0.3/css/style.css (“style-src”).

**Comment by berzniz** [comment]
Thanks for reporting. If anyone wants to take a look at this, please let me know. Otherwise, I'll get to it sometime this month

**Comment by berzniz** [comment]
Will be included in version `1.0.29` thanks to @adambriny

**Comment by marcphilipp** [comment]
Awesome, thanks! 👍
