### ISSUE TITLE
Display file's "view" status in tree 

### ISSUE THREAD

**Issue by david-come-pix4d** [berzniz/github_pr_tree#90]
Hello,

Is it possible to reflect file's "View" status within the tree with little something ? That way we could in a glance see what files have been viewed and those which need review. 

PS: Very nice work, I like this extension !

**Comment by berzniz** [comment]
That feature exists, but it is probably not well done: the un-viewed files are a bit bolder than those already viewed.

We might need to make the bold "bolder" or use a different mark (like a checkmark for viewed files)

**Comment by berzniz** [comment]
Added a checkmark in 1.0.25

**Comment by david-come-pix4d** [comment]
Thank you very much !
